Repository RedisTimeSeries/RedisTimeSeries, pull requests merged in 2020-09, with the labels that each got.

#530 change toc_depth to 3
  mkdocs.yml
Labels: docs

#532 fix #531: change uncompressed chunk `size` and `num_samples` from shor…
  src/chunk.h
  tests/test_module.py
Labels: bug

#534 Fix #527 : Store srcKey to RDB
  src/rdb.c
  tests/test_module.py
Labels: bug

#535 Fixed configuration docs page
  docs/configuration.md
Labels: docs

#539 Change error message
  src/module.c
Labels: enhancement
