Repository RedisTimeSeries/RedisTimeSeries, pull requests merged in 2020-08, with the labels that each got.

#502 Chunksize in bytes instead of samples
  docs/commands.md
  src/chunk.c
  src/chunk.h
  src/compressed_chunk.c
  src/config.c
  src/config.h
  src/consts.h
  src/module.c
  src/rdb.c
  src/rdb.h
  src/tsdb.c
  src/tsdb.h
  src/unittests_compressed_chunk.c
  src/unittests_uncompressed_chunk.c
  tests/test_module.py
  tests/test_rdbs.py
Labels: enhancement

#505 Issue 504 - check for first chunk if fails to retrieve chunk after upsert in the first sample in series
  src/tsdb.c
  tests/test_module.py
Labels: bug

#510 Add Redis Data Source links
  docs/index.md
Labels: docs
