Repository RedisTimeSeries/RedisTimeSeries, pull requests merged in 2020-12, with the labels that each got.

#590 Fixed duplicate policy min/max rules not working for negative values
  src/generic_chunk.c
  src/unittests.c
  src/unittests_uncompressed_chunk.c
  tests/test_module.py
Labels: bug

#608 Updated QA automation tests
  .circleci/config.yml
  tests/qa/RS_VERSIONS
  tests/qa/nightly.json
  tests/qa/release.json
  tests/qa/run
Labels: Development tools

#601 clarify docs around default configuration for DUPLICATE_POLICY
  docs/configuration.md
Labels: docs
