Repository RedisTimeSeries/RedisTimeSeries, pull requests merged in 2021-05, with the labels that each got.

#711 [fix] Fixed crash on Missing keytype check on TS.INCRBY/DECRBY
  src/module.c
  tests/flow/test_negative.py
Labels: bug

#732 Enable tracking OSS standalone redis ingestion performance over CI
  .circleci/config.yml
  src/Makefile
  tests/benchmarks/requirements.txt
  tests/benchmarks/tsbs-devops-ingestion-scale100-4days-keyspace.yml
  tests/benchmarks/tsbs-devops-ingestion-scale100-4days.yml
Labels: performance

#722 Add support for filter by queries
  docs/commands.md
  src/Makefile
  src/abstract_iterator.h
  src/filter_iterator.c
  src/filter_iterator.h
  src/gears_commands.c
  src/gears_integration.c
  src/module.c
  src/query_language.c
  src/query_language.h
  src/reply.c
  src/reply.h
  src/resultset.c
  src/resultset.h
  src/series_iterator.c
  src/series_iterator.h
  src/tsdb.c
  src/tsdb.h
  tests/flow/test_ts_createrule.py
  tests/flow/test_ts_mrange.py
  tests/flow/test_ts_mrange_groupby.py
  tests/flow/test_ts_range.py
Labels: enhancement

#611 Support TS.DEL
  src/chunk.c
  src/chunk.h
  src/compressed_chunk.c
  src/compressed_chunk.h
  src/generic_chunk.c
  src/generic_chunk.h
  src/module.c
  src/tsdb.c
  src/tsdb.h
  tests/flow/test_ts_delete.py
Labels: enhancement

#741 supress thread local vars
  tests/redis_valgrind.sup
Labels: Development tools
