Repository RedisTimeSeries/RedisTimeSeries, pull requests merged in 2021-08, with the labels that each got.

#817 Add keyspace notification on TS.DEL
  src/module.c
  src/tsdb.c
  src/tsdb.h
  tests/flow/test_ts_delete.py
  tests/flow/test_ts_keyspace.py
Labels: enhancement

#818 Fix TS.DEL doc return type
  docs/commands.md
Labels: docs, skip-changelog

#812 Fixup #655, Block align usage only for when explicit timestamps are used
  docs/commands.md
  src/gears_commands.c
  src/gears_integration.c
  src/module.c
  src/query_language.c
  src/tsdb.c
  tests/flow/test_negative.py
  tests/flow/test_ts_mrange.py
  tests/flow/test_ts_range.py
Labels: bug, skip-changelog

#813 Added ENCODING series argument on TS.CREATE/TS.ADD and global config. Deprecate CHUNK_TYPE global config.
  docs/commands.md
  src/config.c
  src/config.h
  src/consts.h
  src/module.c
  src/query_language.c
  src/query_language.h
  src/tsdb.c
  src/tsdb.h
  tests/flow/test_globalconfigs.py
  tests/flow/test_ts_add.py
  tests/flow/test_ts_create.py
Labels: enhancement

#821 fix #820, verify groupby comes after filter
  src/query_language.c
  tests/flow/test_ts_mrange_groupby.py
Labels: bug, skip-changelog

#789 Local cluster benchmarks and profiling
  .gitignore
  src/Makefile
  tests/benchmarks/defaults.yml
  tests/benchmarks/tsbs-devops-ingestion-scale100-4days.yml
  tests/benchmarks/tsbs-scale100-cpu-max-all-1.yml
  tests/benchmarks/tsbs-scale100-cpu-max-all-8.yml
  tests/benchmarks/tsbs-scale100-double-groupby-1.yml
  tests/benchmarks/tsbs-scale100-double-groupby-5.yml
  tests/benchmarks/tsbs-scale100-double-groupby-all.yml
  tests/benchmarks/tsbs-scale100-groupby-orderby-limit.yml
  tests/benchmarks/tsbs-scale100-high-cpu-1.yml
  tests/benchmarks/tsbs-scale100-high-cpu-all.yml
  tests/benchmarks/tsbs-scale100-lastpoint.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-1-1.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-1-12.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-8-1.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-1-1.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-1-12.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-8-1.yml
Labels: skip-changelog

#827 Made TS.ADD BLOCK upsert error more clear towards DUPLICATE_POLICY usage
  src/module.c
Labels: skip-changelog

#828 Fixed small typo on TS.ADD blocked OOO insertion
  src/module.c
Labels: skip-changelog

#834 exclude queryindex, mget, mrange from ramp, delete clean_ramp file (#…
  ramp.yml
  src/clean_ramp.py
Labels: skip-changelog
