Repository RedisTimeSeries/RedisTimeSeries, pull requests merged in 2021-01, with the labels that each got.

#615 TS.MGET/TS.MRANGE: Fixed crash/spurious errors due to inconsistencies between referenced keys on QueryIndexPredicate result dict and the updated labelsIndex
  src/indexer.c
  src/module.c
  src/module.h
  tests/flow/test_ts_mget.py
  tests/flow/test_ts_mrange.py
Labels: bug

#606 Valgrind: leak supression updates.; leak check on every commit; small/medium sized leak fixes.
  .circleci/config.yml
  src/Makefile
  src/chunk.c
  src/compaction.c
  src/rdb.c
  src/tsdb.c
  tests/flow/test_persistency.py
  tests/flow/test_ts_madd.py
  tests/flow/test_ts_mrange.py
  tests/redis_valgrind.sup
Labels: Development tools, bug

#616 Applied clang-format to header files; Fixed test compiler warnings;
  src/Makefile
  src/chunk.h
  src/compaction.h
  src/compressed_chunk.h
  src/config.h
  src/generic_chunk.h
  src/gorilla.h
  src/indexer.h
  src/module.h
  src/parse_policies.h
  src/rdb.h
  src/tsdb.h
  src/unittests_compressed_chunk.c
Labels: Development tools

#622 Ensuring proper string length limit on RMLog calls within ts.mget and ts.mrange errors
  src/module.c
Labels: bug

#628 CircleCI: added abort_for_docs and early_return_for_forked_pull_requests
  .circleci/config.yml
Labels: Development tools

#619 Moved reply and parsing methods from module.c to specific C/header files
  src/Makefile
  src/module.c
  src/query_language.c
  src/query_language.h
  src/reply.c
  src/reply.h
  src/tsdb.c
  src/tsdb.h
Labels: Development tools
