Repository RedisTimeSeries/RedisTimeSeries, pull requests merged in 2021-03, with the labels that each got.

#665 Performance improvement: Using uncompressed series for temporary series on ApplySerieRangeIntoNewSerie
  src/resultset.c
Labels: performance

#667 Performance: Only get and release thread safe context within upsertCompaction() if the serie has compaction rules.
  src/tsdb.c
Labels: performance

#671 Performance: using fpconv (Grisu-algorithm) for floating-point conversion ReplyWithSample()
  src/Makefile
  src/fpconv.c
  src/fpconv.h
  src/fpconv_powers.h
  src/reply.c
Labels: performance

#673 minimum for redis-py now
  tests/flow/Pipfile
Labels: bug

#681 Enable debug/release profiling flags on rmutil and RedisTimeSeries
  build/rmutil/Makefile
  src/Makefile
Labels: Development tools

#682 Performance: Avoid calling ParseDuplicatePolicy() on add() with argv=NULL
  src/module.c
Labels: performance

#688 improve gropuby performance, add temporary flag for a series
  src/module.c
  src/resultset.c
  src/resultset.h
  src/tsdb.c
  src/tsdb.h
Labels: performance
