Repository RedisTimeSeries/RedisTimeSeries, pull requests merged in 2021-09, with the labels that each got.

#844 Introduce `ts_range_90k_datapoints` benchmark
  tests/benchmarks/ts_range_90k_datapoints.yml
Labels: performance

#832 Adds a quickstart page to the docs
  docs/commands.md
  docs/index.md
  docs/quickstart.md
  mkdocs.yml
Labels: docs, skip-changelog

#851 Enabled OSS clustered benchmarks on CI, including targets per benchmark
  .circleci/config.yml
  tests/benchmarks/defaults.yml
  tests/benchmarks/tsbs-devops-ingestion-scale100devices-10metrics-31days.yml
  tests/benchmarks/tsbs-devops-ingestion-scale100devices-10metrics-4days-keyspace.yml
  tests/benchmarks/tsbs-devops-ingestion-scale100devices-10metrics-4days.yml
  tests/benchmarks/tsbs-scale100-cpu-max-all-1.yml
  tests/benchmarks/tsbs-scale100-cpu-max-all-1@4139rps.yml
  tests/benchmarks/tsbs-scale100-cpu-max-all-8.yml
  tests/benchmarks/tsbs-scale100-cpu-max-all-8@588rps.yml
  tests/benchmarks/tsbs-scale100-double-groupby-1.yml
  tests/benchmarks/tsbs-scale100-double-groupby-1@324rps.yml
  tests/benchmarks/tsbs-scale100-double-groupby-5.yml
  tests/benchmarks/tsbs-scale100-double-groupby-5@70rps.yml
  tests/benchmarks/tsbs-scale100-double-groupby-all.yml
  tests/benchmarks/tsbs-scale100-double-groupby-all@35rps.yml
  tests/benchmarks/tsbs-scale100-groupby-orderby-limit.yml
  tests/benchmarks/tsbs-scale100-groupby-orderby-limit@28rps.yml
  tests/benchmarks/tsbs-scale100-high-cpu-1.yml
  tests/benchmarks/tsbs-scale100-high-cpu-1@1816rps.yml
  tests/benchmarks/tsbs-scale100-high-cpu-all.yml
  tests/benchmarks/tsbs-scale100-high-cpu-all@18rps.yml
  tests/benchmarks/tsbs-scale100-lastpoint.yml
  tests/benchmarks/tsbs-scale100-lastpoint@488rps.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-1-1.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-1-12.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-1-12@2320rps.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-1-1@2320rps.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-8-1.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-8-1@4458rps.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-1-1.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-1-12.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-1-12@648rps.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-1-1@648rps.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-8-1.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-8-1@1158rps.yml
Labels: performance, skip-changelog
