Repository RedisTimeSeries/RedisTimeSeries, pull requests merged in 2021-11, with the labels that each got.

#894 adding a label named valgrind, now triggers CI valgrind runs
  .github/workflows/trigger-valgrind.yaml
Labels: valgrind

#897 Overall local benchmark runner improvements. Included 5 shards topology on CI runs.
  src/Makefile
  tests/benchmarks/requirements.txt
  tests/benchmarks/tsbs-scale100-cpu-max-all-1.yml
  tests/benchmarks/tsbs-scale100-cpu-max-all-1@4139rps.yml
  tests/benchmarks/tsbs-scale100-cpu-max-all-8@588rps.yml
  tests/benchmarks/tsbs-scale100-double-groupby-1@324rps.yml
  tests/benchmarks/tsbs-scale100-double-groupby-5@70rps.yml
  tests/benchmarks/tsbs-scale100-double-groupby-all@35rps.yml
  tests/benchmarks/tsbs-scale100-groupby-orderby-limit@28rps.yml
  tests/benchmarks/tsbs-scale100-high-cpu-1@1816rps.yml
  tests/benchmarks/tsbs-scale100-high-cpu-all@18rps.yml
  tests/benchmarks/tsbs-scale100-lastpoint@488rps.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-1-12@2320rps.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-1-1@2320rps.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-8-1@4458rps.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-1-12@648rps.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-1-1@648rps.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-8-1@1158rps.yml
Labels: performance, skip-changelog

#899 Enabled perf profiler on CI (perf|feature|master|version) for oss-clu…
  .circleci/config.yml
  tests/benchmarks/tsbs-scale100-cpu-max-all-1.yml
Labels: performance

#902 fixed mem leak in ts.del flow
  src/tsdb.c
Labels: valgrind
