Repository RedisTimeSeries/RedisTimeSeries, pull requests merged in 2021-02, with the labels that each got.

#617 Added single-shard GROUPBY <label> REDUCE <reducer> to TS.MRANGE
  .circleci/config.yml
  src/Makefile
  src/aggregated_iterator.c
  src/aggregated_iterator.h
  src/module.c
  src/reply.c
  src/resultset.c
  src/resultset.h
  src/series_iterator.c
  src/series_iterator.h
  src/tsdb.c
  src/tsdb.h
  tests/flow/test_persistency.py
  tests/flow/test_ts_mrange_groupby.py
  tests/flow/tests.sh
Labels: enhancement

#651 Fixed GroupList_ApplyReducer() __source__ label building
  src/resultset.c
  tests/flow/test_ts_mrange_groupby.py
Labels: bug

#654 centos-8 system-setup support
  system-setup.py
Labels: Development tools
