Repository RedisTimeSeries/RedisTimeSeries, pull requests merged in 2021-07, with the labels that each got.

#771 Release drafter
  .github/release-drafter-config.yml
  .github/workflows/release-drafter.yml
Labels: skip-changelog

#778 Fixed parseLabelListFromArgs() for label-value pairs with size larger than 255 bytes
  src/indexer.c
  src/indexer.h
  src/query_language.c
  tests/flow/test_ts_mget.py
  tests/flow/test_ts_mrange.py
  tests/flow/test_ts_queryindex.py
Labels: bug

#772 Performance `_seriesIteratorGetNext`: Remove unecessary free/alloc on end of each chunk
  src/chunk.c
  src/chunk.h
  src/compressed_chunk.c
  src/compressed_chunk.h
  src/generic_chunk.c
  src/generic_chunk.h
  src/series_iterator.c
Labels: performance

#784 Enabled high-cpu-* queries (the last missing 2) into CI benchmark automation
  tests/benchmarks/tsbs-scale100-high-cpu-1.yml
  tests/benchmarks/tsbs-scale100-high-cpu-all.yml
Labels: performance

#787 Performance`cpu-max-all-1` +6%: using __bultin_expect within SeriesIteratorGetNext. Remove _seriesIteratorGetNext call
  src/consts.h
  src/gorilla.c
  src/series_iterator.c
Labels: performance

#788 Performance `cpu-max-all-1` +2%: using using __bultin_expect within Compressed_ChunkIteratorGetNext. Remove Compressed_ReadNext call
  src/compressed_chunk.c
  src/compressed_chunk.h
  src/gorilla.c
  src/gorilla.h
Labels: performance

#762 Allow to limit labels during query via the new `SELECTED_LABELS` argument
  src/gears_commands.c
  src/gears_integration.c
  src/gears_integration.h
  src/module.c
  src/query_language.c
  src/query_language.h
  src/redisgears.h
  src/reply.c
  src/reply.h
  src/resultset.c
  src/resultset.h
  tests/flow/test_negative.py
  tests/flow/test_ts_mget.py
  tests/flow/test_ts_mrange.py
  tests/flow/utils.py
Labels: performance, requires-doc-PR

#791 fix memory leak and remove dead code
  src/gears_commands.c
  src/gears_integration.c
  src/reply.c
Labels: bug

#794 Performance tsbs `high-cpu-all`: move `FILTER_BY_TS` feature timestamps lookup time from linear to log(n)
  src/filter_iterator.c
  src/generic_chunk.c
  src/generic_chunk.h
  src/query_language.c
  tests/flow/test_ts_mrange.py
Labels: oss-cluster-performance, performance

#799 release limit labels strings
  src/gears_commands.c
  src/gears_integration.c
Labels: bug, skip-changelog

#803 Added documentation for TS.DEL
  docs/commands.md
Labels: docs, skip-changelog

#810 Enabling the tsbs supported benchmarks on v1.4
  .circleci/config.yml
  tests/benchmarks/requirements.txt
  tests/benchmarks/tsbs-devops-ingestion-scale100-4days-keyspace.yml
  tests/benchmarks/tsbs-devops-ingestion-scale100-4days.yml
  tests/benchmarks/tsbs-scale100-cpu-max-all-8.yml
  tests/benchmarks/tsbs-scale100-double-groupby-5.yml
  tests/benchmarks/tsbs-scale100-double-groupby-all.yml
  tests/benchmarks/tsbs-scale100-lastpoint.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-8-1.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-1-1.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-1-12.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-8-1.yml
Labels: performance, skip-changelog

#801 Fix #655 - Add aggregation alignment option
  docs/commands.md
  src/filter_iterator.c
  src/filter_iterator.h
  src/query_language.c
  src/query_language.h
  src/tsdb.c
  tests/flow/test_negative.py
  tests/flow/test_ts_range.py
Labels: enhancement

#808 [docs] Added documentation and examples for SELECTED_LABELS, GROUPBY/REDUCE, FILTERY_BY_* features added to TS.MRANGE/MREVRANGE
  docs/commands.md
Labels: docs, skip-changelog

#814 TS.DEL should return deleted count
  src/module.c
  src/tsdb.c
  tests/flow/test_ts_delete.py
Labels: bug
