Repository RedisTimeSeries/RedisTimeSeries, pull requests merged in 2022-05, with the labels that each got.

#1159 Fixed benchmarks to use 128B chunk size
  tests/benchmarks/ts_queryindex_100K-series-tsbs-devops.yml
  tests/benchmarks/ts_queryindex_10M-series-tsbs-devops.yml
  tests/benchmarks/ts_queryindex_1M-series-tsbs-devops.yml
  tests/benchmarks/ts_range_90k_datapoints.yml
  tests/benchmarks/tsbs-scale100-cpu-max-all-1.yml
  tests/benchmarks/tsbs-scale100-cpu-max-all-8.yml
  tests/benchmarks/tsbs-scale100-double-groupby-1.yml
  tests/benchmarks/tsbs-scale100-double-groupby-5.yml
  tests/benchmarks/tsbs-scale100-double-groupby-all.yml
  tests/benchmarks/tsbs-scale100-groupby-orderby-limit.yml
  tests/benchmarks/tsbs-scale100-high-cpu-1.yml
  tests/benchmarks/tsbs-scale100-high-cpu-all.yml
  tests/benchmarks/tsbs-scale100-lastpoint.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-1-1.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-1-12.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-8-1.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-1-1.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-1-12.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-8-1.yml
Labels: skip-changelog

#1158 Fixed benchmarks to use 128B chunk size
  tests/benchmarks/tsbs-scale100-cpu-max-all-1.yml
  tests/benchmarks/tsbs-scale100-cpu-max-all-8.yml
  tests/benchmarks/tsbs-scale100-double-groupby-1.yml
  tests/benchmarks/tsbs-scale100-double-groupby-5.yml
  tests/benchmarks/tsbs-scale100-double-groupby-all.yml
  tests/benchmarks/tsbs-scale100-groupby-orderby-limit.yml
  tests/benchmarks/tsbs-scale100-high-cpu-1.yml
  tests/benchmarks/tsbs-scale100-high-cpu-all.yml
  tests/benchmarks/tsbs-scale100-lastpoint.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-1-1.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-1-12.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-8-1.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-1-1.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-1-12.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-8-1.yml
Labels: skip-changelog

#1146 Enable AVX2 for MaxAppendValues
  src/Makefile
  src/compaction.c
  src/compactions/compaction_avx2.c
  src/compactions/compaction_avx2.h
  src/compactions/compaction_common.h
  src/utils/arch_features.c
  src/utils/arch_features.h
Labels: performance

#1134 Add Jedis in clients.md
  docs/docs/clients.md
Labels: docs

#1180 ts.madd bug fix, don't replicate fail additions
  src/module.c
Labels: bug
