Repository RedisTimeSeries/RedisTimeSeries, pull requests merged in 2022-01, with the labels that each got.

#967 Optimize chunk decompress by loop unrolling Compressed_ChunkIteratorGetNext
  src/compressed_chunk.c
Labels: performance

#969 CI benchmarks stabilitization
  .circleci/config.yml
  tests/benchmarks/tsbs-scale100-cpu-max-all-1.yml
  tests/benchmarks/tsbs-scale100-cpu-max-all-1@4139rps.yml
  tests/benchmarks/tsbs-scale100-cpu-max-all-8.yml
  tests/benchmarks/tsbs-scale100-cpu-max-all-8@588rps.yml
  tests/benchmarks/tsbs-scale100-double-groupby-1.yml
  tests/benchmarks/tsbs-scale100-double-groupby-1@324rps.yml
  tests/benchmarks/tsbs-scale100-double-groupby-5.yml
  tests/benchmarks/tsbs-scale100-double-groupby-5@70rps.yml
  tests/benchmarks/tsbs-scale100-double-groupby-all.yml
  tests/benchmarks/tsbs-scale100-double-groupby-all@35rps.yml
  tests/benchmarks/tsbs-scale100-groupby-orderby-limit.yml
  tests/benchmarks/tsbs-scale100-groupby-orderby-limit@28rps.yml
  tests/benchmarks/tsbs-scale100-high-cpu-1.yml
  tests/benchmarks/tsbs-scale100-high-cpu-1@1816rps.yml
  tests/benchmarks/tsbs-scale100-high-cpu-all.yml
  tests/benchmarks/tsbs-scale100-high-cpu-all@18rps.yml
  tests/benchmarks/tsbs-scale100-lastpoint.yml
  tests/benchmarks/tsbs-scale100-lastpoint@488rps.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-1-1.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-1-12.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-1-12@2320rps.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-1-1@2320rps.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-8-1.yml
  tests/benchmarks/tsbs-scale100-single-groupby-1-8-1@4458rps.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-1-1.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-1-12.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-1-12@648rps.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-1-1@648rps.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-8-1.yml
  tests/benchmarks/tsbs-scale100-single-groupby-5-8-1@1158rps.yml
Labels: Development tools, performance, skip-changelog, oss-cluster-performance

#992 set default libmr threadpool size to 3
  src/config.c
Labels: performance, requires-patch-benchmark, oss-cluster-performance

#991 set default libmr threadpool size to 3
  src/config.c
Labels: performance, requires-patch-benchmark, oss-cluster-performance

#1000 Removed a mention of Redis Labs.
  docs/quickstart.md
Labels: docs

#1009 Adds node-redis to client list.
  docs/clients.md
Labels: docs

#1001 Minor typo redis->Redis.
  README.md
Labels: docs
